const ERRORS = {
  HTTP: {
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  },
  DATABASE: {
    CONDITIONAL_CHECK_FAILED: 'CONDITIONAL_CHECK_FAILED',
    ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  },
};

export default ERRORS;
